#+TITLE: First simulation in OpenFOAM

You will learn about:

+ the basic case setup of OpenFOAM
+ the initial values of your simulation
+ the mesh (e.g. the boundaries)
+ running the simulation of the flow in a 2D elbow case with three different meshes
+ post processing

  You will familiarize yourself with the terminal in Linux, where you will run all your simulations in OpenFOAM. You will also get a first idea on the work flow that you have to follow in order to run a successful simulation.

* Setting up the environment:

Fist, copy the elbow tutorial from:

#+begin_src bash
/opt/OpenFOAM/OpenFOAM-v9/tutorials/incompressible/icoFoam/elbow
#+end_src

to your working directory.

Then, convert the GAMBIT mesh to something compatible with OpenFOAM. For that we use:

#+begin_src bash
>fluentMeshToFoam elbow.msh
#+end_src

#+RESULTS:

Now, in /system/controlDict/ we change the simulation time from 10 to 75. For this, we edit the variable /endTime/.
* Running the simulation:

The simulation can be run by typing the solver's name and executing:

#+begin_src bash
>icoFoam
#+end_src

For running the simulation and the solver command (e.g. icoFoam) should be executed inside the copy of the tutorial main folder. For example: the command should be executed in the elbow folder, if it was run at some subfolders or somewhere else, the simulation will fail.
